name: Update Movie Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # Run once a day at 12:00 PM UTC

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python scraper.py
        
      - name: Run Fixer (if necessary)
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python fixer.py

      - name: Clean up temporary files
        if: always() # This step runs even if previous steps fail
        run: |
          rm -f movies_temp.json source_page.html

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add movies.json
          if git diff --staged --quiet; then
            echo "No changes to movies.json to commit."
          else
            git commit -m "Automated: Update movie data"
            git push
          fi
