name: Update Movie Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # Run every 2 hours to be mindful of API calls

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install the NEW dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the scraper, providing the NEW secret as an environment variable
      - name: Run Scraper
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scraper.py

      # This part remains the same
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add movies.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated: Update movie data via Gemini"
            git push
          fi
